language: python
matrix:
  include:
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  allow_failures:
  - python: "3.8-dev"
    dist: xenial
    sudo: true
  - python: "pypy3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip3 install .
before_script:
  - pip3 install python-coveralls
  - pip3 install coverage
# command to run tests, e.g. python setup.py test
script:
  - coverage run --source xenomapper.xenomapper,xenomapper.mappability -m xenomapper.tests.test_all
after_success:
  - coveralls
